#!/usr/bin/python3
# coding: utf-8

# Imports Python
from sys import argv
from os import system


try:
    import requests
    from bs4 import BeautifulSoup
    from urllib.request import urlopen
    from urllib.error import HTTPError
except:
    print("Deseja instalar os requisitos faltantes? [Y/n]")
    vaiInstalar = input()
    if vaiInstalar in ('Y', 'y', 's', 'S'):
        system("sudo pip3 install -r requirements.txt")
    else:
        exit()

# My imports
from parsers.Mails import Mail
from utils.Bouncer import Bouncer
from parsers.Images import Images
from parsers.Lattes import Lattes
from parsers.Server import Server
from utils.Arguments import Getopt
from parsers.PhysicalAddr import Physical
from utils.ExtensionFiles import ExtensionsFile


def printResult(arrayList):
    if arrayList == None or arrayList == []:
        return None
    for element in arrayList:
        if element != None:
            print(element)


uri = ''
html = ''
url = Getopt.requiredArgs(argv, ['-s', '--site']).strip()
bouncer = Bouncer(url)


while uri != None:
    try:
        bouncer.setWordlist('light_wordlist.list')
        uri = bouncer.getCurrentWordFromWordlist()
        if uri is None:
            break
        request = requests.get(url + uri)
        html = request.text
    except HTTPError as error:
        print('Erro de requisição para: ' + url + uri + '.Erro: ' + error)

    if request.status_code == 200:
        # For regex search - String return
        beautifulHTML = BeautifulSoup(html, 'html.parser').prettify()
        # For BeautifulSoup search - encoding string return
        codingHTML = BeautifulSoup(html, 'html.parser')

        print("URL analisada: " + url + uri)

        emails = Mail(html)
        image = Images(codingHTML)
        curriculo = Lattes(beautifulHTML)
        zipcode = Physical(beautifulHTML)

        image.setImages(url + uri)
        curriculo.setLattes()
        emails.setEmails()
print()
position = Server('www.' + bouncer.getDomain())
print(bouncer.getDomain())
print(zipcode.getAddress())
print(position.getGeoLocation())
printResult(emails.getEmails())
printResult(curriculo.getLattes())
printResult(image.getImages())
