#!/usr/bin/python3
# coding: utf-8

# Imports Python
from sys import argv
from os import system

try:
    from bs4 import BeautifulSoup
    from urllib.request import urlopen
    from urllib.error import HTTPError
except:
    print("Deseja instalar os requisitos faltantes? [Y/n]")
    vaiInstalar = input()
    if vaiInstalar in ('Y', 'y', 's', 'S'):
        system("sudo pip3 install -r requirements.txt")
    else:
        exit()

# My imports
from utils.arguments import Getopt
from parsers.mail import Mail
from parsers.lattes import Lattes
from parsers.physical_address import Physical

def printResult(arrayList):
    if arrayList == None or arrayList == []:
        return None
    for element in arrayList:
        if element != None:
            print(element)

def physical_info(html):
    zipcode = Physical(html)
    zipcode.getCep()
    print(zipcode.getAddress())

def mail_info(html):
    emails = Mail(html)
    printResult(emails.get_mails())

def academic_info(html):
    curriculo = Lattes(html)
    printResult(curriculo.get_lattes())

url = Getopt.requiredArgs(argv, ['-s', '--site']).strip()

try:
    html = urlopen(url)
except HTTPError as error:
    print('Erro de requisição para: '+ url + '.Erro: ' + error)
    exit()

gettag = BeautifulSoup(html.read(), 'lxml').prettify()
print("URL analisada: " + url + '\n')

mail_info(gettag)
academic_info(gettag)
physical_info(gettag)
